    name: Deploy to Hetzner

    on:
      push:
        branches:
          - master

    jobs:
      build-and-push:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Create .env file
            run: |
              echo "ENV_FILE=${{ secrets.ENV_FILE }}" >> .env
              cat .env # Optional: Print the .env file content for debugging
          - name: Login to GHCR
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ secrets.GHCR_USERNAME }}
              password: ${{ secrets.GHCR_TOKEN }}
          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ghcr.io/${{ github.repository }}:latest

      deploy:
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
          - name: SSH into Hetzner server
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.HETZNER_HOST }}
              username: ${{ secrets.HETZNER_USER }}
              key: ${{ secrets.HETZNER_SSH_KEY }}
              script: |
                echo "DOCKER_COMPOSE=${{ variables.DOCKER_COMPOSE }}" > docker-compose.yml
                cat docker-compose.yml
                echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
                docker pull ghcr.io/${{ github.repository }}:latest
                docker stop genshin-helper || true
                docker rm genshin-helper || true
                docker compose up -d
                docker logout ghcr.io
